### ISSUE TITLE
Port to circuit python for adafruit controllers

### ISSUE THREAD

**Issue by namron1967** [FRC4564/Maestro#12]
Can the Maestro PY class be configured to work for circuit python?  This would be a fantastic combination to be able to use the maestro servo controller with the adafruit feather microcontroller using circuit python.

**Comment by FRC4564** [comment]
Certainly doable, with a couple of caveats.  The Maestro is 5 volt (TTL) so unless the feather would be 5v tolerant, you would need a level shifter to protect it.  Second, the maestro should be run on its own serial port for communications.  I'm assuming the feather uses REPL over a serial port already, so to have both REPL and the maestro working at the same time you'd need two ports.  Not sure if the feather supports that.  Once you get past the h/w requirements, it should be fairly straight forward to alter maestro.py to work.  The actual commands to send a byte of data may be different under MicroPython, but once that is sorted out the code changes would be minimal and isolated to the __init__, sendCmd, and close methods.

The maestro does provide some nice features for controlling servos, but you could take a look at a the PCA9685 for basic servo position control.  Its a low-cost alternative that communicates over i2c.  It would be easy to connect, from a h/w perspective, and Adafruit has a MicroPython library for it.

**Comment by namron1967** [comment]
Hi Steve,

  The feather M4 Express uses the micro usb cable to connect to your pc /
repl. It has a hardware serial port for sure. Here'she the pinouts for it.
What do you think? I wouldn'the mind using the servo featherwing board but
I really wanted to use the Pololu Maestro scripts setup as a bunch of sub
routines and be able to call them from the M4 board with a small circuit
python program.

Norman

**Comment by namron1967** [comment]
Steve,

  Here is some more info on the Feather M4 Express board. I asked some
questions on the forum and here's the reply....

The ATSAMD51 has 8 SERCOMs that can be configured as USARTS as well as SPI
or I2C.

No, the it has hardware USB support, completely separate from the board's
Rx/Tx pins.

For using two hardware UARTs with the Feather M4, please see
https://learn.adafruit.com/remote-iot-environmental-sensor. In that project
I used the serial GPS featherwing and a serial air quality sensor.




Norman Sockwell
Sci-Fi Metropolis LLC.
250 Hamilton Ln.
Riverside, Al. 35135
205-602-0798
www.scifimetropolis.com
scifimetropolis@gmail.com

**Comment by namron1967** [comment]
Hi Steven,

  Did you get my last email? Just checking. Do you think that you could do
the conversion from python to micropython for this? What do you think it
would cost if you could?

Thanks, Norman


Norman Sockwell
Sci-Fi Metropolis LLC.
250 Hamilton Ln.
Riverside, Al. 35135
205-602-0798
www.scifimetropolis.com
scifimetropolis@gmail.com

**Comment by FRC4564** [comment]
Hi Norman,

I don’t have a Feather to work with so it’s not something that I can readily do.  And I’ve got other project commitments that would take priority.  Was this something you needed quickly? If so, perhaps some others in the community could lend a hand.

Steve

Steve

________________________________

**Comment by namron1967** [comment]
Steven,

  I could send you one of my feather boards and a pololu boards for testing
if you like. How long do you think it would take, cost, ect? If you don't
have time, can you recommend someone? I would like to have it in the next
couple of weeks if possible.

Thanks, Norman


Norman Sockwell
Sci-Fi Metropolis LLC.
250 Hamilton Ln.
Riverside, Al. 35135
205-602-0798
www.scifimetropolis.com
scifimetropolis@gmail.com

**Comment by namron1967** [comment]
The other reason for using the Pololu Maestro is the you can control
speed and acceleration of the servos. The featherwing 8 channel servo board
doesn't seem to be able to adjust either. Just does movement apparently.

Norman
